version: '3.9'

services:
  database:
    container_name: database
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=graduationProjectInJava
    image: postgres:latest
    networks:
      - database-project

  project:
    container_name: project
    image: dernakblr/graduatio:v1.3.5
    ports:
    - "8080:8080"
    environment:
     - DB_HOST=database
    depends_on:
      - database
    networks:
      - database-project

networks:
  database-project:
    driver: bridge


